server {
    listen       80;
    server_name  localhost;
    root   /usr/share/nginx/html;
    index  index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /sso/      { proxy_pass http://mall-portal:8085; proxy_set_header Host $host; }
    location /member/   { proxy_pass http://mall-portal:8085; proxy_set_header Host $host; }
    location /product/  { proxy_pass http://mall-portal:8085; proxy_set_header Host $host; }
    location /cart/     { proxy_pass http://mall-portal:8085; proxy_set_header Host $host; }
    location /order/    { proxy_pass http://mall-portal:8085; proxy_set_header Host $host; }
    location /alipay/   { proxy_pass http://mall-portal:8085; proxy_set_header Host $host; }
    location /home/     { proxy_pass http://mall-portal:8085; proxy_set_header Host $host; }
    location /brand/    { proxy_pass http://mall-portal:8085; proxy_set_header Host $host; }
    location /coupon/   { proxy_pass http://mall-portal:8085; proxy_set_header Host $host; }
    location /assistant/ { proxy_pass http://mall-assistant:8086; proxy_set_header Host $host; }
}
